@server = http://localhost:4004
@me = Authorization: Basic {{$processEnv USER}}:
@basic = Authorization: Basic admin:admin
### ------------------------------------------------------------------------
# Get Weight
GET  {{server}}/v2/catalog/getWeight 
content-type: application/json
{{me}}



### ------------------------------------------------------------------------
# Get Parcel
GET  {{server}}/v2/catalog/Parcel
content-type: application/json
{{me}}

### ------------------------------------------------------------------------
# Get Parcel ONLY ID
GET  {{server}}/v2/catalog/Airline
content-type: application/json
{{me}}

### ------------------------------------------------------------------------
# Delete Parcel
DELETE   {{server}}/v2/catalog/Parcel(5e3199a2-c3a5-434f-8848-6ab95ff761d8) 
content-type: application/json
{{me}} 

### ------------------------------------------------------------------------
# Get Parcel ONLY ID
GET  {{server}}/v2/catalog/Package
content-type: application/json
{{me}}



### ------------------------------------------------------------------------
# Get CargoReceipt
GET  {{server}}/v2/catalog/CargoReceipt(c95cddc6-077e-4a78-aaaa-b90e82419d79) 
content-type: application/json
{{me}}

### ------------------------------------------------------------------------
# Delete CargoReceipt
DELETE   {{server}}/v2/catalog/Parcel(c95cddc6-077e-4a78-aaaa-b90e82419d79) 
content-type: application/json
{{me}} 

### ------------------------------------------------------------------------
# Get CargoReceipt ONLY ID
GET  {{server}}/v2/catalog/CargoReceipt?$select=ID,preParcel
content-type: application/json
{{me}}



### ------------------------------------------------------------------------
# Patch CargoReceipt
PATCH   {{server}}/v2/catalog/CargoReceipt(c95cddc6-077e-4a78-aaaa-b90e82419d79) 
content-type: application/json
{{me}} 

{
    "image": ""
}
### ------------------------------------------------------------------------
# Delete CargoReceipt
DELETE   {{server}}/v2/catalog/CargoReceipt(c95cddc6-077e-4a78-aaaa-b90e82419d79) 
content-type: application/json






### ------------------------------------------------------------------------
# Post Airline
GET  {{server}}/v2/catalog/Airline
content-type: application/json
{{me}}


### ------------------------------------------------------------------------
# Post Airline
GET http://opengtindb.org/?ean=7894900011517&amp;cmd=query&amp;queryid=400000000
content-type: application/json