@server = http://localhost:4004
@me = Authorization: Basic {{$processEnv USER}}:
@basic = Authorization: Basic admin:admin
### ------------------------------------------------------------------------
# Get EAN
GET  {{server}}/catalogRest/getEAN 
content-type: application/json
{{me}}
